// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ritp.proto

package ritp;

public interface HeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ritp.Header)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   *Consumer的功能名，此功能名应是一个可以在服务中心注册的服务方法
   * </pre>
   *
   * <code>string fn = 1;</code>
   * @return The fn.
   */
  String getFn();
  /**
   * <pre>
   *Consumer的功能名，此功能名应是一个可以在服务中心注册的服务方法
   * </pre>
   *
   * <code>string fn = 1;</code>
   * @return The bytes for fn.
   */
  com.google.protobuf.ByteString
      getFnBytes();

  /**
   * <pre>
   *数据，可以包含生产者的信息、消费者需要的数据等
   * </pre>
   *
   * <code>bytes data = 2;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <pre>
   *数据类型
   * </pre>
   *
   * <code>string data_type = 3;</code>
   * @return The dataType.
   */
  String getDataType();
  /**
   * <pre>
   *数据类型
   * </pre>
   *
   * <code>string data_type = 3;</code>
   * @return The bytes for dataType.
   */
  com.google.protobuf.ByteString
      getDataTypeBytes();

  /**
   * <pre>
   *Msg.buf的类型
   * </pre>
   *
   * <code>string buf_type = 4;</code>
   * @return The bufType.
   */
  String getBufType();
  /**
   * <pre>
   *Msg.buf的类型
   * </pre>
   *
   * <code>string buf_type = 4;</code>
   * @return The bytes for bufType.
   */
  com.google.protobuf.ByteString
      getBufTypeBytes();

  /**
   * <pre>
   *Consumer处理结果的输出地址， 例："accReply", "wss://hostname:8080/path?fn=accReply"
   * </pre>
   *
   * <code>string output_to = 5;</code>
   * @return The outputTo.
   */
  String getOutputTo();
  /**
   * <pre>
   *Consumer处理结果的输出地址， 例："accReply", "wss://hostname:8080/path?fn=accReply"
   * </pre>
   *
   * <code>string output_to = 5;</code>
   * @return The bytes for outputTo.
   */
  com.google.protobuf.ByteString
      getOutputToBytes();
}
