// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ritp.proto

package ritp;

public interface InfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ritp.Info)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string version = 1;</code>
   * @return The version.
   */
  String getVersion();
  /**
   * <code>string version = 1;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>bytes data = 2;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>string data_type = 3;</code>
   * @return The dataType.
   */
  String getDataType();
  /**
   * <code>string data_type = 3;</code>
   * @return The bytes for dataType.
   */
  com.google.protobuf.ByteString
      getDataTypeBytes();
}
