// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ritp.proto

package ritp;

/**
 * <pre>
 *本端信息
 * </pre>
 *
 * Protobuf type {@code ritp.Info}
 */
public  final class Info extends
    com.google.protobuf.GeneratedMessageLite<
        Info, Info.Builder> implements
    // @@protoc_insertion_point(message_implements:ritp.Info)
    InfoOrBuilder {
  private Info() {
    version_ = "";
    data_ = com.google.protobuf.ByteString.EMPTY;
    dataType_ = "";
  }
  public static final int VERSION_FIELD_NUMBER = 1;
  private String version_;
  /**
   * <code>string version = 1;</code>
   * @return The version.
   */
  @Override
  public String getVersion() {
    return version_;
  }
  /**
   * <code>string version = 1;</code>
   * @return The bytes for version.
   */
  @Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(version_);
  }
  /**
   * <code>string version = 1;</code>
   * @param value The version to set.
   */
  private void setVersion(
      String value) {
    value.getClass();
  
    version_ = value;
  }
  /**
   * <code>string version = 1;</code>
   */
  private void clearVersion() {
    
    version_ = getDefaultInstance().getVersion();
  }
  /**
   * <code>string version = 1;</code>
   * @param value The bytes for version to set.
   */
  private void setVersionBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    version_ = value.toStringUtf8();
    
  }

  public static final int DATA_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString data_;
  /**
   * <code>bytes data = 2;</code>
   * @return The data.
   */
  @Override
  public com.google.protobuf.ByteString getData() {
    return data_;
  }
  /**
   * <code>bytes data = 2;</code>
   * @param value The data to set.
   */
  private void setData(com.google.protobuf.ByteString value) {
    value.getClass();
  
    data_ = value;
  }
  /**
   * <code>bytes data = 2;</code>
   */
  private void clearData() {
    
    data_ = getDefaultInstance().getData();
  }

  public static final int DATA_TYPE_FIELD_NUMBER = 3;
  private String dataType_;
  /**
   * <code>string data_type = 3;</code>
   * @return The dataType.
   */
  @Override
  public String getDataType() {
    return dataType_;
  }
  /**
   * <code>string data_type = 3;</code>
   * @return The bytes for dataType.
   */
  @Override
  public com.google.protobuf.ByteString
      getDataTypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(dataType_);
  }
  /**
   * <code>string data_type = 3;</code>
   * @param value The dataType to set.
   */
  private void setDataType(
      String value) {
    value.getClass();
  
    dataType_ = value;
  }
  /**
   * <code>string data_type = 3;</code>
   */
  private void clearDataType() {
    
    dataType_ = getDefaultInstance().getDataType();
  }
  /**
   * <code>string data_type = 3;</code>
   * @param value The bytes for dataType to set.
   */
  private void setDataTypeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    dataType_ = value.toStringUtf8();
    
  }

  public static Info parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static Info parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static Info parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static Info parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static Info parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static Info parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static Info parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static Info parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static Info parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static Info parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static Info parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static Info parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(Info prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   *本端信息
   * </pre>
   *
   * Protobuf type {@code ritp.Info}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        Info, Builder> implements
      // @@protoc_insertion_point(builder_implements:ritp.Info)
      InfoOrBuilder {
    // Construct using ritp.Info.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string version = 1;</code>
     * @return The version.
     */
    @Override
    public String getVersion() {
      return instance.getVersion();
    }
    /**
     * <code>string version = 1;</code>
     * @return The bytes for version.
     */
    @Override
    public com.google.protobuf.ByteString
        getVersionBytes() {
      return instance.getVersionBytes();
    }
    /**
     * <code>string version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        String value) {
      copyOnWrite();
      instance.setVersion(value);
      return this;
    }
    /**
     * <code>string version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      copyOnWrite();
      instance.clearVersion();
      return this;
    }
    /**
     * <code>string version = 1;</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setVersionBytes(value);
      return this;
    }

    /**
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    @Override
    public com.google.protobuf.ByteString getData() {
      return instance.getData();
    }
    /**
     * <code>bytes data = 2;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setData(value);
      return this;
    }
    /**
     * <code>bytes data = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      copyOnWrite();
      instance.clearData();
      return this;
    }

    /**
     * <code>string data_type = 3;</code>
     * @return The dataType.
     */
    @Override
    public String getDataType() {
      return instance.getDataType();
    }
    /**
     * <code>string data_type = 3;</code>
     * @return The bytes for dataType.
     */
    @Override
    public com.google.protobuf.ByteString
        getDataTypeBytes() {
      return instance.getDataTypeBytes();
    }
    /**
     * <code>string data_type = 3;</code>
     * @param value The dataType to set.
     * @return This builder for chaining.
     */
    public Builder setDataType(
        String value) {
      copyOnWrite();
      instance.setDataType(value);
      return this;
    }
    /**
     * <code>string data_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataType() {
      copyOnWrite();
      instance.clearDataType();
      return this;
    }
    /**
     * <code>string data_type = 3;</code>
     * @param value The bytes for dataType to set.
     * @return This builder for chaining.
     */
    public Builder setDataTypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDataTypeBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ritp.Info)
  }
  @Override
  @SuppressWarnings({"unchecked", "fallthrough"})
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new Info();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          Object[] objects = new Object[] {
            "version_",
            "data_",
            "dataType_",
          };
          String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\n" +
              "\u0003\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<Info> parser = PARSER;
        if (parser == null) {
          synchronized (Info.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<Info>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ritp.Info)
  private static final Info DEFAULT_INSTANCE;
  static {
    Info defaultInstance = new Info();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Info.class, defaultInstance);
  }

  public static Info getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Info> PARSER;

  public static com.google.protobuf.Parser<Info> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

